# dataset = {'Calcium Carbonate': ['Safe', 'abrasive, buffering agent, bulking agent, opacifying agent, oral care agent, buffering, bulking, opacifying, and oral care', 'Suspected nano-scale ingredients with potential to absorb into the skin'],
# 'Water':['Safe', 'Solvent', 'Classified as not expected to be potentially toxic or harmful'],
# 'Sorbitol': ['Safe', 'flavoring agent, fragrance ingredient, humectant, skin-conditioning agent - humectant, plasticiser, and skin conditioning', 'Designated as safe for general or specific, limited use in food'],
# 'Hydrated Silica': ['Safe', 'abrasive, absorbent, anticaking agent, bulking agent, opacifying agent, oral care agent;skin-conditioning agent - miscellaneous, viscosity increasing agent - aqueous, anticaking, bulking, opacifying, and viscosity controlling', 'Persistent, bioaccumulative in wildlife and humans'],
# 'Sodium Lauryl Sulfate': ['Toxic', 'denaturant, surfactant - cleansing agent, cleansing, emulsifying, foaming, and surfactant', 'Originally used to clean floors, sodium lauryl sulfate is a detergent known to cause microscopic tears in the mouth (which can lead to canker sores).'],
# 'Herbal Extract' : ['Safe','fragrance ingredient and skin-conditioning agent - miscellaneous', 'Endocrine disruption (moderate)'],
# 'Flavour' : ['Moderate', 'Different flavour components can give breath-freshening benefits by masking odours and can provide cooling or warming sensations within the mouth during and after brushing.', 'Classified as not expected to be potentially toxic or harmful'],
# 'Xanthan Gum' : ['Safe', 'binder, emulsion stabilizer, skin-conditioning agent - miscellaneous', 'Irritation from this ingredient is rare, with the most common side effect being bloating or gas.'],
# 'Sodium Silicate' : ['Moderate', 'buffering agent, corrosion inhibitor, ph adjuster, anticorrosive, and buffering', 'Use restrictions (low), Non-reproductive organ system toxicity (moderate), and Irritation (skin, eyes, or lungs) (moderate)'],
# 'Benzyl alcohol' : ['Moderate', 'external analgesic, fragrance ingredient, oral health care drug, preservative, solvent;viscosity decreasing agent, masking, and solvent', 'Use restrictions (moderate), Non-reproductive organ system toxicity (moderate), and Occupational hazards (high)'],
# 'Sodium Benzoate' : ['Safe', 'fragrance ingredient, preservative, anticorrosive, and masking', 'Use restrictions (moderate) and Non-reproductive organ system toxicity (low)'],
# 'Sodium Saccharin' : ['Moderate', 'flavoring agent, fragrance ingredient, masking, and oral care', 'Limited or incomplete evidence of cancer according to safety/hazard data'],
# 'Iron Oxides' : ['Safe', 'colorant and cosmetic colorant', 'Enhanced skin absorption, Persistence and bioaccumulation (high), and Non-reproductive organ system toxicity (low)'],
# 'Silica' : ['Safe', 'abrasive, absorbent, anticaking agent, bulking agent, opacifying agent, suspending agent- nonsurfactant, anticaking, and opacifying', 'Persistence and bioaccumulation (high) and Non-reproductive organ system toxicity (low)'],
# 'Sodium Monofluorophosphate' : ['Moderate', 'anticaries agent, oral care agent, antiplaque, and oral care', 'Use restrictions (moderate) and Non-reproductive organ system toxicity (low)'],
# 'Sodium Carboxymethyl Cellulose' : ['Safe', 'plays the part of adhesion and moulding', 'Classified as not expected to be potentially toxic or harmful'],
# 'Sodium Chloride' : ['Safe', 'flavoring agent, oral care agent, and viscosity increasing agent - aqueous', 'Classified as not expected to be potentially toxic or harmful'],
# 'Sodium Bicarbonate' : ['Safe', 'abrasive, buffering agent, deodorant agent, oral care agent, oral health care drug;phadjuster, skin protectant, buffering, deodorant, oral care, and skin protecting', 'Classified as not expected to be potentially toxic or harmful'],
# 'Pigment Blue' : ['Moderate', 'colorant and cosmetic colorant', 'Use restrictions (high) and Non-reproductive organ system toxicity (low)'],
# 'Sodium Lauryl Ether Sulfate' : ['Toxic', 'surfactant - cleansing agent, surfactant - emulsifying agent, and cleansing', 'Use restrictions (low), Non-reproductive organ system toxicity (moderate), Irritation (skin, eyes, or lungs) (moderate), and Contamination concerns (high)'],
# 'Propylene Glycol' : ['Moderate', 'fragrance ingredient, humectant, skin-conditioning agent - humectant, skin-conditioningagent - miscellaneous, solvent, viscosity decreasing agent, skin conditioning, and viscosity controlling', 'Propylene glycol is a small organic alcohol commonly used as a skin conditioning agent. It has been associated with irritant and allergic contact dermatitis as well as contact urticaria in humans; these sensitization effects can be manifested at propylene glycol concentrations as low as 2%'],
# 'Polysorbat-20' : ['Moderate', 'fragrance ingredient, surfactant - emulsifying agent, and surfactant - solubilizing agent', 'Non-reproductive organ system toxicity (low) and Contamination concerns (high)'],
# 'Ascorbic Acid 2 Glucoside' : ['Safe', 'antioxidant, fragrance ingredient, ph adjuster, skin-conditioning agent - miscellaneous, buffering, masking, and skin conditioning', '-'],
# 'Citric Acid' : ['Safe', 'chelating agent, fragrance ingredient, ph adjuster, buffering, chelating, and masking', 'Use restrictions (moderate)'],
# 'Glycerin' : ['Safe', 'denaturant, fragrance ingredient, hair conditioning agent, humectant, oral care agent;oral health care drug, skin-conditioning agent - humectant, skin protectant, viscosity decreasing agent, perfuming, and solvent', 'Use restrictions (moderate)'],
# 'Disodium EDTA' : ['Moderate', 'chelating agent, chelating, and viscosity controlling', 'Enhanced skin absorption'],
# 'Preservative' : ['Moderate', 'Preservatives in cosmetics prevent bacteria from growing.', 'Preservatives in cosmetics are used to prevent bacterial and microbial growth, but synthetic versions can cause adverse long term health effects. Parabens and formaldehyde-releasing ingredients are commonly used in conventional products, but studies have shown the harmful effects of exposure to these ingredients'],
# 'Grape Seed Oil' : ['Safe', 'skin-conditioning agent - miscellaneous, emollient, and skin conditioning', '-'],
# 'Sodium Palmate' : ['Safe', 'Sodium palmate is a core ingredient in many types of soap and is made from palm oil.', 'The chemical has been verified to be of low concern'],
# 'Sodium Palm Kernelate' : ['Safe', 'common ingredient in soap that helps cleanse skin and acts as an emulsifying ingredient.', 'this can lead to inflammation which may cause breakouts. This isn’t likely, but it’s possible if you have really sensitive skin.'],
# 'Talc' : ['Toxic', 'abrasive, absorbent, anticaking agent, bulking agent, opacifying agent, skin protectant;slip modifier, anticaking, bulking, opacifying, and skin protecting', 'Use restrictions (high), Non-reproductive organ system toxicity (moderate), and Contamination concerns (high)'],
# 'Parfum' : ['Toxic', 'deodorant, masking, and perfuming', 'Endocrine disruption (moderate), Non-reproductive organ system toxicity (moderate), Ecotoxicology (low), and Irritation (skin, eyes, or lungs) (moderate)'],
# 'PEG-7 Amodimethicone' : ['Moderate', 'skin-conditioning agent - emollient, hair conditioning, and humectant', 'Non-reproductive organ system toxicity (low) and Contamination concerns (high)'],
# 'Etidronic Acid' : ['Safe', 'chelating agent and chelating', 'Use restrictions (moderate)'],
# 'Triclocarban': ['Moderate', 'cosmetic biocide, deodorant agent, preservative, and deodorant', 'Use restrictions (moderate), Endocrine disruption (low), Persistence and bioaccumulation (moderate), Non-reproductive organ system toxicity (moderate), and Ecotoxicology (low)'],
# 'Acetic Acid' : ['Safe', 'fragrance ingredient, ph adjuster, buffering, and masking', 'Non-reproductive organ system toxicity (moderate) and Irritation (skin, eyes, or lungs) (moderate)'],
# 'Methylchloroisothiazolinone' : ['Moderate', 'preservative', 'Use restrictions (high), Ecotoxicology (low), and Irritation (skin, eyes, or lungs) (moderate)'],
# 'Methylisothiazolinone' : ['Toxic', 'preservative', 'Use restrictions (high), Neurotoxicity (low), Ecotoxicology (low), and Irritation (skin, eyes, or lungs) (moderate)'],
# 'Butylphenyl Methylpropional' : ['Toxic', 'fragrance ingredient and masking', 'Use restrictions (moderate), Endocrine disruption (low), Persistence and bioaccumulation (moderate), and Non-reproductive organ system toxicity (moderate)'],
# 'Aqua' : ['Safe', 'Solvent', 'Classified as not expected to be potentially toxic or harmful'],
# 'Citronellol' : ['Moderate', 'fragrance ingredient and masking', ' Its LIKELY UNSAFE to inhale citronellol. Lung damage has been reported.'],
# 'Limonene' : ['Moderate', 'perfuming', 'Use restrictions (moderate), Ecotoxicology (low), and Irritation (skin, eyes, or lungs) (high)'],
# 'Linalool' : ['Moderate', 'fragrance ingredient, deodorant, and masking', 'It can cause sensitivity and irritation, particularly in sensitive skin types. '],
# 'Cl 77891' : ['Moderate', 'colorant, opacifying agent, sunscreen agent, and ultraviolet light absorber', 'Non-reproductive organ system toxicity (moderate) and Occupational hazards (high)'],
# 'Cl 11680' : ['Moderate', 'cosmetic dye', 'Use restrictions (high), Ecotoxicology (low), Irritation (skin, eyes, or lungs) (high), and Occupational hazards (high)'],
# 'Trideceth-10' : [],
# 'Palm Acid' : [],
# 'Palm Kernel Acid' : [],
# 'Sodium Phenylphenate' : [],
# 'Sodium C14-16 Olefin Sulfonate' : [],
# 'Tetrasodium EDTA' : [],
# 'Tetrabutyl Ammonium Bromide' : [],
# 'Hydroxypropyl Cyclodextrin' : []}


dataset = {'Calcium Carbonate': ['Safe', 'abrasive, buffering agent, bulking agent, opacifying agent, oral care agent, buffering, bulking, opacifying, and oral care', 'Suspected nano-scale ingredients with potential to absorb into the skin'],
'Water':['Safe', 'Solvent', 'Classified as not expected to be potentially toxic or harmful'],
'Sorbitol': ['Safe', 'flavoring agent, fragrance ingredient, humectant, skin-conditioning agent - humectant, plasticiser, and skin conditioning', 'Designated as safe for general or specific, limited use in food'],
'Hydrated Silica': ['Safe', 'abrasive, absorbent, anticaking agent, bulking agent, opacifying agent, oral care agent;skin-conditioning agent - miscellaneous, viscosity increasing agent - aqueous, anticaking, bulking, opacifying, and viscosity controlling', 'Persistent, bioaccumulative in wildlife and humans'],
'Sodium Lauryl Sulfate': ['Toxic', 'denaturant, surfactant - cleansing agent, cleansing, emulsifying, foaming, and surfactant', 'Originally used to clean floors, sodium lauryl sulfate is a detergent known to cause microscopic tears in the mouth (which can lead to canker sores).'],
'Herbal Extract' : ['Safe','fragrance ingredient and skin-conditioning agent - miscellaneous', 'Endocrine disruption (moderate)'],
'Flavour' : ['Moderate', 'Different flavour components can give breath-freshening benefits by masking odours and can provide cooling or warming sensations within the mouth during and after brushing.', 'Classified as not expected to be potentially toxic or harmful'],
'Xanthan Gum' : ['Safe', 'binder, emulsion stabilizer, skin-conditioning agent - miscellaneous', 'Irritation from this ingredient is rare, with the most common side effect being bloating or gas.'],
'Sodium Silicate' : ['Moderate', 'buffering agent, corrosion inhibitor, ph adjuster, anticorrosive, and buffering', 'Use restrictions (low), Non-reproductive organ system toxicity (moderate), and Irritation (skin, eyes, or lungs) (moderate)'],
'Benzyl alcohol' : ['Moderate', 'external analgesic, fragrance ingredient, oral health care drug, preservative, solvent;viscosity decreasing agent, masking, and solvent', 'Use restrictions (moderate), Non-reproductive organ system toxicity (moderate), and Occupational hazards (high)'],
'Sodium Benzoate' : ['Safe', 'fragrance ingredient, preservative, anticorrosive, and masking', 'Use restrictions (moderate) and Non-reproductive organ system toxicity (low)'],
'Sodium Saccharin' : ['Moderate', 'flavoring agent, fragrance ingredient, masking, and oral care', 'Limited or incomplete evidence of cancer according to safety/hazard data'],
'Iron Oxides' : ['Safe', 'colorant and cosmetic colorant', 'Enhanced skin absorption, Persistence and bioaccumulation (high), and Non-reproductive organ system toxicity (low)'],
'Silica' : ['Safe', 'abrasive, absorbent, anticaking agent, bulking agent, opacifying agent, suspending agent- nonsurfactant, anticaking, and opacifying', 'Persistence and bioaccumulation (high) and Non-reproductive organ system toxicity (low)'],
'Sodium Monofluorophosphate' : ['Moderate', 'anticaries agent, oral care agent, antiplaque, and oral care', 'Use restrictions (moderate) and Non-reproductive organ system toxicity (low)'],
'Sodium Carboxymethyl Cellulose' : ['Safe', 'plays the part of adhesion and moulding', 'Classified as not expected to be potentially toxic or harmful'],
'Sodium Chloride' : ['Safe', 'flavoring agent, oral care agent, and viscosity increasing agent - aqueous', 'Classified as not expected to be potentially toxic or harmful'],
'Sodium Bicarbonate' : ['Safe', 'abrasive, buffering agent, deodorant agent, oral care agent, oral health care drug;phadjuster, skin protectant, buffering, deodorant, oral care, and skin protecting', 'Classified as not expected to be potentially toxic or harmful'],
'Pigment Blue' : ['Moderate', 'colorant and cosmetic colorant', 'Use restrictions (high) and Non-reproductive organ system toxicity (low)'],
'Sodium Lauryl Ether Sulfate' : ['Toxic', 'surfactant - cleansing agent, surfactant - emulsifying agent, and cleansing', 'Use restrictions (low), Non-reproductive organ system toxicity (moderate), Irritation (skin, eyes, or lungs) (moderate), and Contamination concerns (high)'],
'Propylene Glycol' : ['Moderate', 'fragrance ingredient, humectant, skin-conditioning agent - humectant, skin-conditioningagent - miscellaneous, solvent, viscosity decreasing agent, skin conditioning, and viscosity controlling', 'Propylene glycol is a small organic alcohol commonly used as a skin conditioning agent. It has been associated with irritant and allergic contact dermatitis as well as contact urticaria in humans; these sensitization effects can be manifested at propylene glycol concentrations as low as 2%'],
'Polysorbat-20' : ['Moderate', 'fragrance ingredient, surfactant - emulsifying agent, and surfactant - solubilizing agent', 'Non-reproductive organ system toxicity (low) and Contamination concerns (high)'],
'Ascorbic Acid 2 Glucoside' : ['Safe', 'antioxidant, fragrance ingredient, ph adjuster, skin-conditioning agent - miscellaneous, buffering, masking, and skin conditioning', '-'],
'Citric Acid' : ['Safe', 'chelating agent, fragrance ingredient, ph adjuster, buffering, chelating, and masking', 'Use restrictions (moderate)'],
'Glycerin' : ['Safe', 'denaturant, fragrance ingredient, hair conditioning agent, humectant, oral care agent;oral health care drug, skin-conditioning agent - humectant, skin protectant, viscosity decreasing agent, perfuming, and solvent', 'Use restrictions (moderate)'],
'Disodium EDTA' : ['Moderate', 'chelating agent, chelating, and viscosity controlling', 'Enhanced skin absorption'],
'Preservative' : ['Moderate', 'Preservatives in cosmetics prevent bacteria from growing.', 'Preservatives in cosmetics are used to prevent bacterial and microbial growth, but synthetic versions can cause adverse long term health effects. Parabens and formaldehyde-releasing ingredients are commonly used in conventional products, but studies have shown the harmful effects of exposure to these ingredients'],
'Grape Seed Oil' : ['Safe', 'skin-conditioning agent - miscellaneous, emollient, and skin conditioning', '-'],
'Sodium Palmate' : ['Safe', 'Sodium palmate is a core ingredient in many types of soap and is made from palm oil.', 'The chemical has been verified to be of low concern'],
'Sodium Palm Kernelate' : ['Safe', 'common ingredient in soap that helps cleanse skin and acts as an emulsifying ingredient.', 'this can lead to inflammation which may cause breakouts. This isn’t likely, but it’s possible if you have really sensitive skin.'],
'Talc' : ['Toxic', 'abrasive, absorbent, anticaking agent, bulking agent, opacifying agent, skin protectant;slip modifier, anticaking, bulking, opacifying, and skin protecting', 'Use restrictions (high), Non-reproductive organ system toxicity (moderate), and Contamination concerns (high)'],
'Parfum' : ['Toxic', 'deodorant, masking, and perfuming', 'Endocrine disruption (moderate), Non-reproductive organ system toxicity (moderate), Ecotoxicology (low), and Irritation (skin, eyes, or lungs) (moderate)'],
'PEG-7 Amodimethicone' : ['Moderate', 'skin-conditioning agent - emollient, hair conditioning, and humectant', 'Non-reproductive organ system toxicity (low) and Contamination concerns (high)'],
'Etidronic Acid' : ['Safe', 'chelating agent and chelating', 'Use restrictions (moderate)'],
'Triclocarban': ['Moderate', 'cosmetic biocide, deodorant agent, preservative, and deodorant', 'Use restrictions (moderate), Endocrine disruption (low), Persistence and bioaccumulation (moderate), Non-reproductive organ system toxicity (moderate), and Ecotoxicology (low)'],
'Acetic Acid' : ['Safe', 'fragrance ingredient, ph adjuster, buffering, and masking', 'Non-reproductive organ system toxicity (moderate) and Irritation (skin, eyes, or lungs) (moderate)'],
'Methylchloroisothiazolinone' : ['Moderate', 'preservative', 'Use restrictions (high), Ecotoxicology (low), and Irritation (skin, eyes, or lungs) (moderate)'],
'Methylisothiazolinone' : ['Toxic', 'preservative', 'Use restrictions (high), Neurotoxicity (low), Ecotoxicology (low), and Irritation (skin, eyes, or lungs) (moderate)'],
'Butylphenyl Methylpropional' : ['Toxic', 'fragrance ingredient and masking', 'Use restrictions (moderate), Endocrine disruption (low), Persistence and bioaccumulation (moderate), and Non-reproductive organ system toxicity (moderate)'],
'Aqua' : ['Safe', 'Solvent', 'Classified as not expected to be potentially toxic or harmful'],
'Citronellol' : ['Moderate', 'fragrance ingredient and masking', ' Its LIKELY UNSAFE to inhale citronellol. Lung damage has been reported.'],
'Limonene' : ['Moderate', 'perfuming', 'Use restrictions (moderate), Ecotoxicology (low), and Irritation (skin, eyes, or lungs) (high)'],
'Linalool' : ['Moderate', 'fragrance ingredient, deodorant, and masking', 'It can cause sensitivity and irritation, particularly in sensitive skin types. '],
'Cl 77891' : ['Moderate', 'colorant, opacifying agent, sunscreen agent, and ultraviolet light absorber', 'Non-reproductive organ system toxicity (moderate) and Occupational hazards (high)'],
'Cl 11680' : ['Moderate', 'cosmetic dye', 'Use restrictions (high), Ecotoxicology (low), Irritation (skin, eyes, or lungs) (high), and Occupational hazards (high)'],
'Trideceth-10' : [],
'Palm Acid' : [],
'Palm Kernel Acid' : [],
'Sodium Phenylphenate' : [],
'Sodium C14-16 Olefin Sulfonate' : [],
'Tetrasodium EDTA' : [],
'Tetrabutyl Ammonium Bromide' : [],
'Hydroxypropyl Cyclodextrin' : [],
'Purified Water':['Safe','used for oral and topical products and in granulation processes','Water purification systems must be maintained regularl'],
'Sodium Lauryl Ether Sulphate':['Moderate',' printing and dyeing industry, petroleum and leather industry as lubricant','Irritation(Health: SLS and SLES can irritate)'],
'Cocamidopropyl Betaine':['Moderate','foam booster in shampoos, emulsifying agent, thickener, antistatic agent','allergic reaction, Skin discomfort, Irritation(eyes)'],
'Glycerin':['Safe',' moisturizer to treat or prevent dry, rough, scaly, itchy skin and minor skin irritations','Excessive bowel activity, Cramping,Rectal irritation,Cramping rectal pain'],
'PEG-7 Glyceryl Cocoate':['Safe','formulation of hair dyes and colors, shampoos, cleaning products','Allergic reaction, Glycerin laxative-anal, Bowel irritation'],
'Polyquaternium-7':['Safe','Used as modifier in shampoos, face washs, gel','Doesnt have any side effect but drowsiness, dizziness could be some'],
'Sodium PCA':['Safe','used as a conditioning agent','not to be used with nitrosating agent products'],
'Phenoxyethanol':['Safe',' used as a preservative or stabilizer for other ingredients that might otherwise deteriorate','Blistering Skin, Irritation(skin,eyes)'],
'Fragrance':['Moderate','Use in perfume, airfreshner for pleasant odor','Headaches,Irritation(eyes,nose,throat), Nausea'],
'Sodium Chloride':['Safe','Used to flavor and preserve foods, Used foralleviate dehydration','redness of the skin, shortness of Breath'],
'Sweet Orange Peel Oil':['Moderate','Antimicrobial activity, Aromatherapy with orange essential oil appears to reduce symptoms of anxiety and depression','inflammation, stinging, and photosensitivity'],
'Sandalwood Oil':['Safe',' it is anti-inflammatory, anti-microbial, anti-acne and anti-tanning','skin irritation, rash (contact dermatitis)'],
'Sodium Benzoate':['Moderate',' corrosion inhibitor, fragrance ingredient, and preservative,anti-fungal','Possible side effects are itching and swelling'],
'Potassium Sorbate':['Safe','mild preservative, inhibits microorganisms growth','can cause skin or scalp irritation'],
'Disodium EDTA':['Safe','cleaning use, as it enables cosmetic products to foam','too much Disodium EDTA can cause nausea, vomiting, diarrhea, low blood pressure, fever, and skin issues '],
'Color CI 15510':['Moderate','coloring agent allowed for use in all cosmetics and personal care products','This substance is considered a mild skin irritant'],
'Trideceth-10':['Toxic','used as defoaming agents in paper and paperboard, and in coatings of paper','PEGs (including Trideceth-10) can contain harmful impurities, including: Ethylene Oxide, known to increase the incidences of uterine and breast cancers'],
'Palm Acid':['Safe','used for making laundry soaps and for producing calcium soaps for animal feed formulations','Palm oil is POSSIBLY SAFE when used as a medicine, short-term'],
'Palm kernel Acid':['Safe','A mixture of fatty acids derived from palm oil. Used as a cleansing agent, emulsifier, or to add opacity to cosmetic products','if taken, can increase levels of "bad" low-density lipoprotein cholesterol'],
'Sodium PhenylPhenate':['Safe','use as disinfectants, antimicrobials, preservatives, antioxidants','can cause skin irritation'],
'Sodium C14-16 Olefin Sulfonate':['Moderate','Its tricky to include in formulas due to stability issues, but it does produce copious foam',' irritating for skin and scalp'],
'Tetrasodium EDTA':['Safe','helps maintain clarity, protect fragrance compounds, and prevent rancidity','There are no known side effects of tetrasodium EDTA'],
'Tetrabutyl Ammonium Bromide':['Toxic','used as a phase transfer catalyst','Irritation(skin,eyes),may cause respiratory irritation'],
'Hydroxypropyl Cyclodextrin':['Moderate','A plant- derived or synthetic carbohydrate that functions as a chelating agent and stabilizer','Potential side effects are Irritation(eyes,skin)'],
'Sodium Hypochlorite':['Toxic','disinfection of viruses, bacteria, fungi, and mycobacterium','severe redness or irritation of treated skin'],
'Sodium Carbonate':['Moderate','Chemical manufacturing, Pulp and paper products',' effects such as respiratory tract irritation, coughing, shortness of breath, and pulmonary edema'],
'Poly':['Toxic',' used as a coagulant in water purification. It is effective in coagulating and flocculating inorganic and organic particles such as silt, clay, algae, bacteria and viruses','Very toxic to aquatic organisms. labored breathing, and cyanosis) and a feeling of apprehension, restlessness'],
'Sodium Hydroxide':['Toxic','used to make soap and as a main ingredient in household products such as liquid drain cleaners',' can cause severe burns and immediate vomiting, nausea, diarrhea or chest and stomach pain'],
'Polyacrylic Acid':['Toxic','used in disposable diapers, ion exchange resins, adhesives and detergents','eye swelling, eye pain, itchy eye, eye redness, increased tear production'],
'Sodium Bisulfite Terminated':['Toxic',' used in making paper and leather, as a food preservative and in dye and chemical production','low future exposure can cause itching and a skin rash'],
'Sodium Laureth Sulphate':['Moderate','used in the printing and dyeing industry, petroleum and leather industry as lubricant, dyeing agent, cleanser, foaming agent and degreasing agent',' can irritate eyes, skin, and lungs, especially with long-term use'],
'Sodium Citrate':['Toxic','acts as a buffering agent in cosmetics products to control their pH level. It can also be used as a preservative','include numbness or tingly feeling, swelling or rapid weight gain, muscle twitching or cramps, fast or slow heart rate'],
'Sodium Xylenesulfonate':['Moderate',' is used in liquid household detergents and shampoos, in degreasing compounds and printing pastes','It can cause eye irritation but is not anticipated to result in skin irritation or sensitization'],
'Cocamide Mea':['Moderate','Cocamide MEA is used in the formulation of bath soaps and shampoo','nhalation of MEA by humans is toxic'],
'Glycol Disterate':['Safe','used as an emollient in cosmetic products, and is a combination of ethylene glycol (colorless chemical) and stearic acid','The Cosmetic Ingredient Review (CIR) Expert Panel reported no human skin irritation or sensitization from glycol distearate'],
'Stearyl Alcohol':['Safe',' used as an emollient, emulsifier, and thickener in a variety of cosmetics and personal care products','burning, stinging, redness, or irritation may occur'],
'Cetyl Alcohol':['Safe','used in the cosmetic industry as an opacifier in shampoos, or as an emollient', 'burning, stinging, redness, or irritation may occur'],
'Guar Hydroxypropyltrimonium Chloride':['Safe',' used as an anti-static agent and hair or skin conditioner; it also increases viscosity, used as hair detangler','No adverse side effects could be find'],
'Trisodium Ethylenediamine Disuccinate':['Moderate','Removes Hair Detox','May cause irritation on sensitive skins. May cause mild transient irritation to the eyes'],
'polyquaternium-6':['Moderate','Its high Antistatic, Film forming, Skin conditioning, Viscosity controlling nature makes it useful as a conditioner in skin and hair care formulation',' It is generally no side effect'],
'Trihydroxystearin':['Safe', 'used as a skin-conditioning agent, a solvent and a viscosity-increasing agent', 'making this shampoo thicker and more spreadable','Can cause irritation in scalp(rare)'],
'PALMITIC ACID':['Safe','Used to produce soaps, cosmetics, and industrial mold release agents','Topical palmitic acid is not known to cause side effects'],
'NIACINAMIDE':['Moderate','Niacinamide helps build keratin , a type of protein that keeps your skin firm and healthy, Treats hyperpigmentation','minor side effects such as stomach upset, gas, dizziness, rash, itching, and other problems'],
'DIMETHICONE':['Safe',' It acts as an anti-foaming agent, skin protectant and skin & hair conditioner','Alergic reaction, rash, itching, dizziness'],
'ETHYLHEXYL METHOXYCINNAMATE':['Safe','Used in cosmetics and personal care products as a sunscreen agent to protect the skin, and as an ultraviolet light absorber to protect products','Not much of any harm, but bad for animals'],
'BUTYL METHOXYDIBENZOYLMETHANE':['Safe',' Used in a wide range of cosmetic products to provide an appropriate Sun Protection Factor (SPF) in sunscreens or to protect cosmetics against UV radiation','Causes skin rashes, allergic reactions and inflammation'],
'TITANIUM DIOXIDE':['Safe','Used in a variety of personal care products, including sunscreens, pressed powders, and loose powders, as a UV filter or whitening agent.','inhalation: At high concentrations: can irritate the nose and throat, mild irritation'],
'SODIUM ASCORBYL PHOSPHATE':['Safe',' It protects the skin, promotes its development and improves its appearance','Moderate irritant and sensitizer as well as an eye irritant'],
'ISOPROPYL MYRISTATE':['Safe','Used in cosmetics and topical medical preparations to ameliorate the skin absorption',' small chance of skin irritation, clogged pores and acne inflammation'],
'TOCOPHERYL ACETATE':['Moderate','Helps fight free radical damage and promote skin healing to diminish signs of aging.','Dizziness, Headache, rash'],
'ALLANTOIN':['Safe','Used as a moisturizer to treat or prevent dry, rough, scaly, itchy skin and minor skin irritations','owever, burning, stinging, redness, or irritation may occur.'],
'PYRIDOXINE HYDROCHLORIDE':['Safe','Used in the formulation of bath products, soaps and detergents, cleansing products','can cause side effects when taken in large doses for a long time like nausea, numbness in arms/legs'],
'PHENOXYETHANOL':['Safe','Used as an antibacterial and/or a preservative to prevent products from losing their potency or spoiling.','It irritates skin and eyes, and can cause blistering on skin as well'],
'METHYLPARABEN':['Moderate','Effective at preventing microbial growth and germs such as bacteria and mold in skincare and cosmetic formulations','Itching, bumps and blisters, dry and scaly skin'],
'PROPYLPARABEN':['Safe','Used in cosmetics to prevent the growth of harmful bacteria and mold, in order to protect both the products and consumers',' can cause a variety of reactions to those with allergies. They are known to cause skin irritation'],
'POTASSIUM HYDROXIDE':['Toxic',' Used in small amounts in cosmetics to modulate the pH of a product','Contact with skin can cause irritation or severe burns and scarring with greater exposures.'],
'ALPHA-ISOMETHYL IONONE':['Safe','Is used in the formulation of aftershave lotions, bath products, bubble baths, hair care products, moisturizers, perfumes and colognes, shampoos and skin care products','has the potential to cause a skin reaction (such as red, bumpy, or itchy skin)'],
'BENZYL SALICYLATE':['Safe',' It is used as a solvent for crystalline synthetic musks and as a component and fixative in floral perfumes such as carnation','skin, eye, nose and throat irritants which can cause severe symptoms such as a burning sensation, nausea'],
'BUTYLPHENYL METHYLPROPIONAL':['Safe','Ssed in aftershave lotions, bath products, bubble baths, cleansing products, hair care products',' known dermal and respiratory irritant'],
'CITRONELLOL':['Safe','It has BB-cream like formula which offers instant tone perfection, elegant matte finish and efficient anti-UV B protection',' It might cause skin reactions or irritation in some people. When inhaled: Its LIKELY Unsafe to inhale citronella oil'],
'GERANIOL':['Safe','rt functions as a fragrance, masking (decreases or inhibits the basic odor in the product) and tonic (creates a feeling of well-being of the products on skin and hair) ingredient','A bit pour of itching'],
'HEXYL CINNAMAL':['Toxic','Used in perfumes and other beauty products as a fragrance additive.','The ingredient is known to cause contact allergy, which means that it can cause an allergic reaction to your skin'],
'COUMARIN':['Moderate','Used in the formulation of aftershave lotions, bath products, bubble baths, cleansing products, moisturizers','nausea, diarrhea or blurred vision may occur at first as your body adjusts to the medication']
}


# dataset = {'Calcium Carbonate': ['Safe', 'abrasive, buffering agent, bulking agent, opacifying agent, oral care agent, buffering, bulking, opacifying, and oral care', 'Suspected nano-scale ingredients with potential to absorb into the skin'],
# 'Water':['Safe', 'Solvent', 'Classified as not expected to be potentially toxic or harmful'],
# 'Sorbitol': ['Safe', 'flavoring agent, fragrance ingredient, humectant, skin-conditioning agent - humectant, plasticiser, and skin conditioning', 'Designated as safe for general or specific, limited use in food'],
# 'Hydrated Silica': ['Safe', 'abrasive, absorbent, anticaking agent, bulking agent, opacifying agent, oral care agent;skin-conditioning agent - miscellaneous, viscosity increasing agent - aqueous, anticaking, bulking, opacifying, and viscosity controlling', 'Persistent, bioaccumulative in wildlife and humans'],
# 'Sodium Lauryl Sulfate': ['Toxic', 'denaturant, surfactant - cleansing agent, cleansing, emulsifying, foaming, and surfactant', 'Originally used to clean floors, sodium lauryl sulfate is a detergent known to cause microscopic tears in the mouth (which can lead to canker sores).'],
# 'Herbal Extract' : ['Safe','fragrance ingredient and skin-conditioning agent - miscellaneous', 'Endocrine disruption (moderate)'],
# 'Flavour' : ['Moderate', 'Different flavour components can give breath-freshening benefits by masking odours and can provide cooling or warming sensations within the mouth during and after brushing.', 'Classified as not expected to be potentially toxic or harmful'],
# 'Xanthan Gum' : ['Safe', 'binder, emulsion stabilizer, skin-conditioning agent - miscellaneous', 'Irritation from this ingredient is rare, with the most common side effect being bloating or gas.'],
# 'Sodium Silicate' : ['Moderate', 'buffering agent, corrosion inhibitor, ph adjuster, anticorrosive, and buffering', 'Use restrictions (low), Non-reproductive organ system toxicity (moderate), and Irritation (skin, eyes, or lungs) (moderate)'],
# 'Benzyl alcohol' : ['Moderate', 'external analgesic, fragrance ingredient, oral health care drug, preservative, solvent;viscosity decreasing agent, masking, and solvent', 'Use restrictions (moderate), Non-reproductive organ system toxicity (moderate), and Occupational hazards (high)'],
# 'Sodium Benzoate' : ['Safe', 'fragrance ingredient, preservative, anticorrosive, and masking', 'Use restrictions (moderate) and Non-reproductive organ system toxicity (low)'],
# 'Sodium Saccharin' : ['Moderate', 'flavoring agent, fragrance ingredient, masking, and oral care', 'Limited or incomplete evidence of cancer according to safety/hazard data'],
# 'Iron Oxides' : ['Safe', 'colorant and cosmetic colorant', 'Enhanced skin absorption, Persistence and bioaccumulation (high), and Non-reproductive organ system toxicity (low)'],
# 'Silica' : ['Safe', 'abrasive, absorbent, anticaking agent, bulking agent, opacifying agent, suspending agent- nonsurfactant, anticaking, and opacifying', 'Persistence and bioaccumulation (high) and Non-reproductive organ system toxicity (low)'],
# 'Sodium Monofluorophosphate' : ['Moderate', 'anticaries agent, oral care agent, antiplaque, and oral care', 'Use restrictions (moderate) and Non-reproductive organ system toxicity (low)'],
# 'Sodium Carboxymethyl Cellulose' : ['Safe', 'plays the part of adhesion and moulding', 'Classified as not expected to be potentially toxic or harmful'],
# 'Sodium Chloride' : ['Safe', 'flavoring agent, oral care agent, and viscosity increasing agent - aqueous', 'Classified as not expected to be potentially toxic or harmful'],
# 'Sodium Bicarbonate' : ['Safe', 'abrasive, buffering agent, deodorant agent, oral care agent, oral health care drug;phadjuster, skin protectant, buffering, deodorant, oral care, and skin protecting', 'Classified as not expected to be potentially toxic or harmful'],
# 'Pigment Blue' : ['Moderate', 'colorant and cosmetic colorant', 'Use restrictions (high) and Non-reproductive organ system toxicity (low)'],
# 'Sodium Lauryl Ether Sulfate' : ['Toxic', 'surfactant - cleansing agent, surfactant - emulsifying agent, and cleansing', 'Use restrictions (low), Non-reproductive organ system toxicity (moderate), Irritation (skin, eyes, or lungs) (moderate), and Contamination concerns (high)'],
# 'Propylene Glycol' : ['Moderate', 'fragrance ingredient, humectant, skin-conditioning agent - humectant, skin-conditioningagent - miscellaneous, solvent, viscosity decreasing agent, skin conditioning, and viscosity controlling', 'Propylene glycol is a small organic alcohol commonly used as a skin conditioning agent. It has been associated with irritant and allergic contact dermatitis as well as contact urticaria in humans; these sensitization effects can be manifested at propylene glycol concentrations as low as 2%'],
# 'Polysorbat-20' : ['Moderate', 'fragrance ingredient, surfactant - emulsifying agent, and surfactant - solubilizing agent', 'Non-reproductive organ system toxicity (low) and Contamination concerns (high)'],
# 'Ascorbic Acid 2 Glucoside' : ['Safe', 'antioxidant, fragrance ingredient, ph adjuster, skin-conditioning agent - miscellaneous, buffering, masking, and skin conditioning', '-'],
# 'Citric Acid' : ['Safe', 'chelating agent, fragrance ingredient, ph adjuster, buffering, chelating, and masking', 'Use restrictions (moderate)'],
# 'Glycerin' : ['Safe', 'denaturant, fragrance ingredient, hair conditioning agent, humectant, oral care agent;oral health care drug, skin-conditioning agent - humectant, skin protectant, viscosity decreasing agent, perfuming, and solvent', 'Use restrictions (moderate)'],
# 'Disodium EDTA' : ['Moderate', 'chelating agent, chelating, and viscosity controlling', 'Enhanced skin absorption'],
# 'Preservative' : ['Moderate', 'Preservatives in cosmetics prevent bacteria from growing.', 'Preservatives in cosmetics are used to prevent bacterial and microbial growth, but synthetic versions can cause adverse long term health effects. Parabens and formaldehyde-releasing ingredients are commonly used in conventional products, but studies have shown the harmful effects of exposure to these ingredients'],
# 'Grape Seed Oil' : ['Safe', 'skin-conditioning agent - miscellaneous, emollient, and skin conditioning', '-'],
# 'Sodium Palmate' : ['Safe', 'Sodium palmate is a core ingredient in many types of soap and is made from palm oil.', 'The chemical has been verified to be of low concern'],
# 'Sodium Palm Kernelate' : ['Safe', 'common ingredient in soap that helps cleanse skin and acts as an emulsifying ingredient.', 'this can lead to inflammation which may cause breakouts. This isn’t likely, but it’s possible if you have really sensitive skin.'],
# 'Talc' : ['Toxic', 'abrasive, absorbent, anticaking agent, bulking agent, opacifying agent, skin protectant;slip modifier, anticaking, bulking, opacifying, and skin protecting', 'Use restrictions (high), Non-reproductive organ system toxicity (moderate), and Contamination concerns (high)'],
# 'Parfum' : ['Toxic', 'deodorant, masking, and perfuming', 'Endocrine disruption (moderate), Non-reproductive organ system toxicity (moderate), Ecotoxicology (low), and Irritation (skin, eyes, or lungs) (moderate)'],
# 'PEG-7 Amodimethicone' : ['Moderate', 'skin-conditioning agent - emollient, hair conditioning, and humectant', 'Non-reproductive organ system toxicity (low) and Contamination concerns (high)'],
# 'Etidronic Acid' : ['Safe', 'chelating agent and chelating', 'Use restrictions (moderate)'],
# 'Triclocarban': ['Moderate', 'cosmetic biocide, deodorant agent, preservative, and deodorant', 'Use restrictions (moderate), Endocrine disruption (low), Persistence and bioaccumulation (moderate), Non-reproductive organ system toxicity (moderate), and Ecotoxicology (low)'],
# 'Acetic Acid' : ['Safe', 'fragrance ingredient, ph adjuster, buffering, and masking', 'Non-reproductive organ system toxicity (moderate) and Irritation (skin, eyes, or lungs) (moderate)'],
# 'Methylchloroisothiazolinone' : ['Moderate', 'preservative', 'Use restrictions (high), Ecotoxicology (low), and Irritation (skin, eyes, or lungs) (moderate)'],
# 'Methylisothiazolinone' : ['Toxic', 'preservative', 'Use restrictions (high), Neurotoxicity (low), Ecotoxicology (low), and Irritation (skin, eyes, or lungs) (moderate)'],
# 'Butylphenyl Methylpropional' : ['Toxic', 'fragrance ingredient and masking', 'Use restrictions (moderate), Endocrine disruption (low), Persistence and bioaccumulation (moderate), and Non-reproductive organ system toxicity (moderate)'],
# 'Aqua' : ['Safe', 'Solvent', 'Classified as not expected to be potentially toxic or harmful'],
# 'Citronellol' : ['Moderate', 'fragrance ingredient and masking', ' Its LIKELY UNSAFE to inhale citronellol. Lung damage has been reported.'],
# 'Limonene' : ['Moderate', 'perfuming', 'Use restrictions (moderate), Ecotoxicology (low), and Irritation (skin, eyes, or lungs) (high)'],
# 'Linalool' : ['Moderate', 'fragrance ingredient, deodorant, and masking', 'It can cause sensitivity and irritation, particularly in sensitive skin types. '],
# 'Cl 77891' : ['Moderate', 'colorant, opacifying agent, sunscreen agent, and ultraviolet light absorber', 'Non-reproductive organ system toxicity (moderate) and Occupational hazards (high)'],
# 'Cl 11680' : ['Moderate', 'cosmetic dye', 'Use restrictions (high), Ecotoxicology (low), Irritation (skin, eyes, or lungs) (high), and Occupational hazards (high)'],
# 'Trideceth-10' : [],
# 'Palm Acid' : [],
# 'Palm Kernel Acid' : [],
# 'Sodium Phenylphenate' : [],
# 'Sodium C14-16 Olefin Sulfonate' : [],
# 'Tetrasodium EDTA' : [],
# 'Tetrabutyl Ammonium Bromide' : [],
# 'Hydroxypropyl Cyclodextrin' : [],
# 'Purified Water':['Safe','used for oral and topical products and in granulation processes','Water purification systems must be maintained regularl'],
# 'Sodium Lauryl Ether Sulphate':['Moderate',' printing and dyeing industry, petroleum and leather industry as lubricant','Irritation(Health: SLS and SLES can irritate)'],
# 'Cocamidopropyl Betaine':['Moderate','foam booster in shampoos, emulsifying agent, thickener, antistatic agent','allergic reaction, Skin discomfort, Irritation(eyes)'],
# 'Glycerin':['Safe',' moisturizer to treat or prevent dry, rough, scaly, itchy skin and minor skin irritations','Excessive bowel activity, Cramping,Rectal irritation,Cramping rectal pain'],
# 'PEG-7 Glyceryl Cocoate':['Safe','formulation of hair dyes and colors, shampoos, cleaning products','Allergic reaction, Glycerin laxative-anal, Bowel irritation'],
# 'Polyquaternium-7':['Safe','Used as modifier in shampoos, face washs, gel','Doesnt have any side effect but drowsiness, dizziness could be some'],
# 'Sodium PCA':['Safe','used as a conditioning agent','not to be used with nitrosating agent products'],
# 'Phenoxyethanol':['Safe',' used as a preservative or stabilizer for other ingredients that might otherwise deteriorate','Blistering Skin, Irritation(skin,eyes)'],
# 'Fragrance':['Moderate','Use in perfume, airfreshner for pleasant odor','Headaches,Irritation(eyes,nose,throat), Nausea'],
# 'Sodium Chloride':['Safe','Used to flavor and preserve foods, Used foralleviate dehydration','redness of the skin, shortness of Breath'],
# 'Sweet Orange Peel Oil':['Moderate','Antimicrobial activity, Aromatherapy with orange essential oil appears to reduce symptoms of anxiety and depression','inflammation, stinging, and photosensitivity'],
# 'Sandalwood Oil':['Safe',' it is anti-inflammatory, anti-microbial, anti-acne and anti-tanning','skin irritation, rash (contact dermatitis)'],
# 'Sodium Benzoate':['Moderate',' corrosion inhibitor, fragrance ingredient, and preservative,anti-fungal','Possible side effects are itching and swelling'],
# 'Potassium Sorbate':['Safe','mild preservative, inhibits microorganisms growth','can cause skin or scalp irritation'],
# 'Disodium EDTA':['Safe','cleaning use, as it enables cosmetic products to foam','too much Disodium EDTA can cause nausea, vomiting, diarrhea, low blood pressure, fever, and skin issues '],
# 'Color CI 15510':['Moderate','coloring agent allowed for use in all cosmetics and personal care products','This substance is considered a mild skin irritant'],
# 'Trideceth-10':['Toxic','used as defoaming agents in paper and paperboard, and in coatings of paper','PEGs (including Trideceth-10) can contain harmful impurities, including: Ethylene Oxide, known to increase the incidences of uterine and breast cancers'],
# 'Palm Acid':['Safe','used for making laundry soaps and for producing calcium soaps for animal feed formulations','Palm oil is POSSIBLY SAFE when used as a medicine, short-term'],
# 'Palm kernel Acid':['Safe','A mixture of fatty acids derived from palm oil. Used as a cleansing agent, emulsifier, or to add opacity to cosmetic products','if taken, can increase levels of "bad" low-density lipoprotein cholesterol'],
# 'Sodium PhenylPhenate':['Safe','use as disinfectants, antimicrobials, preservatives, antioxidants','can cause skin irritation'],
# 'Sodium C14-16 Olefin Sulfonate':['Moderate','Its tricky to include in formulas due to stability issues, but it does produce copious foam',' irritating for skin and scalp'],
# 'Tetrasodium EDTA':['Safe','helps maintain clarity, protect fragrance compounds, and prevent rancidity','There are no known side effects of tetrasodium EDTA'],
# 'Tetrabutyl Ammonium Bromide':['Toxic','used as a phase transfer catalyst','Irritation(skin,eyes),may cause respiratory irritation'],
# 'Hydroxypropyl Cyclodextrin':['Moderate','A plant- derived or synthetic carbohydrate that functions as a chelating agent and stabilizer','Potential side effects are Irritation(eyes,skin)'],
# 'Sodium Hypochlorite':['Toxic','disinfection of viruses, bacteria, fungi, and mycobacterium','severe redness or irritation of treated skin'],
# 'Sodium Carbonate':['Moderate','Chemical manufacturing, Pulp and paper products',' effects such as respiratory tract irritation, coughing, shortness of breath, and pulmonary edema'],
# 'Poly(diallyldimethylammonium chloride)':['Toxic',' used as a coagulant in water purification. It is effective in coagulating and flocculating inorganic and organic particles such as silt, clay, algae, bacteria and viruses','Very toxic to aquatic organisms. labored breathing, and cyanosis) and a feeling of apprehension, restlessness'],
# 'Sodium Hydroxide':['Toxic','used to make soap and as a main ingredient in household products such as liquid drain cleaners',' can cause severe burns and immediate vomiting, nausea, diarrhea or chest and stomach pain'],
# 'Polyacrylic acid':['Toxic','used in disposable diapers, ion exchange resins, adhesives and detergents','eye swelling, eye pain, itchy eye, eye redness, increased tear production'],
# 'Sodium Bisulphate Terminated':['Toxic',' used in making paper and leather, as a food preservative and in dye and chemical production','low future exposure can cause itching and a skin rash'],
# 'Sodium Laureth Sulphate':['Moderate','used in the printing and dyeing industry, petroleum and leather industry as lubricant, dyeing agent, cleanser, foaming agent and degreasing agent',' can irritate eyes, skin, and lungs, especially with long-term use'],
# 'Sodium Citrate':['Toxic','acts as a buffering agent in cosmetics products to control their pH level. It can also be used as a preservative','include numbness or tingly feeling, swelling or rapid weight gain, muscle twitching or cramps, fast or slow heart rate'],
# 'Sodium Xylenesulfonate':['Moderate',' is used in liquid household detergents and shampoos, in degreasing compounds and printing pastes','It can cause eye irritation but is not anticipated to result in skin irritation or sensitization'],
# 'Cocamide Mea':['Moderate','Cocamide MEA is used in the formulation of bath soaps and shampoo','nhalation of MEA by humans is toxic'],
# 'Glycol Disterate':['Safe','used as an emollient in cosmetic products, and is a combination of ethylene glycol (colorless chemical) and stearic acid','The Cosmetic Ingredient Review (CIR) Expert Panel reported no human skin irritation or sensitization from glycol distearate'],
# 'Stearyl Alcohol':['Safe',' used as an emollient, emulsifier, and thickener in a variety of cosmetics and personal care products','burning, stinging, redness, or irritation may occur'],
# 'Cetyl Alcohol':['Safe','used in the cosmetic industry as an opacifier in shampoos, or as an emollient', 'burning, stinging, redness, or irritation may occur'],
# 'Guar Hydroxypropyltrimonium Chloride':['Safe',' used as an anti-static agent and hair or skin conditioner; it also increases viscosity, used as hair detangler','No adverse side effects could be find'],
# 'Trisodium Ethylenediamine Disuccinate':['Moderate','Removes Hair Detox','May cause irritation on sensitive skins. May cause mild transient irritation to the eyes'],
# 'polyquaternium-6':['Moderate','Its high Antistatic, Film forming, Skin conditioning, Viscosity controlling nature makes it useful as a conditioner in skin and hair care formulation',' It is generally no side effect'],
# 'Trihydroxystearin':['Safe', 'used as a skin-conditioning agent, a solvent and a viscosity-increasing agent', 'making this shampoo thicker and more spreadable','Can cause irritation in scalp(rare)'],
# 'PALMITIC ACID':['Safe','Used to produce soaps, cosmetics, and industrial mold release agents','Topical palmitic acid is not known to cause side effects'],
# 'NIACINAMIDE':['Moderate','Niacinamide helps build keratin , a type of protein that keeps your skin firm and healthy, Treats hyperpigmentation','minor side effects such as stomach upset, gas, dizziness, rash, itching, and other problems'],
# 'DIMETHICONE':['Safe',' It acts as an anti-foaming agent, skin protectant and skin & hair conditioner','Alergic reaction, rash, itching, dizziness'],
# 'ETHYLHEXYL METHOXYCINNAMATE':['Safe','Used in cosmetics and personal care products as a sunscreen agent to protect the skin, and as an ultraviolet light absorber to protect products','Not much of any harm, but bad for animals'],
# 'BUTYL METHOXYDIBENZOYLMETHANE':['Safe',' Used in a wide range of cosmetic products to provide an appropriate Sun Protection Factor (SPF) in sunscreens or to protect cosmetics against UV radiation','Causes skin rashes, allergic reactions and inflammation'],
# 'TITANIUM DIOXIDE':['Safe','Used in a variety of personal care products, including sunscreens, pressed powders, and loose powders, as a UV filter or whitening agent.','inhalation: At high concentrations: can irritate the nose and throat, mild irritation'],
# 'SODIUM ASCORBYL PHOSPHATE':['Safe',' It protects the skin, promotes its development and improves its appearance','Moderate irritant and sensitizer as well as an eye irritant'],
# 'ISOPROPYL MYRISTATE':['Safe','Used in cosmetics and topical medical preparations to ameliorate the skin absorption',' small chance of skin irritation, clogged pores and acne inflammation'],
# 'TOCOPHERYL ACETATE':['Moderate','Helps fight free radical damage and promote skin healing to diminish signs of aging.','Dizziness, Headache, rash'],
# 'ALLANTOIN':['Safe','Used as a moisturizer to treat or prevent dry, rough, scaly, itchy skin and minor skin irritations','owever, burning, stinging, redness, or irritation may occur.'],
# 'PYRIDOXINE HYDROCHLORIDE':['Safe','Used in the formulation of bath products, soaps and detergents, cleansing products','can cause side effects when taken in large doses for a long time like nausea, numbness in arms/legs'],
# 'PHENOXYETHANOL':['Safe','Used as an antibacterial and/or a preservative to prevent products from losing their potency or spoiling.','It irritates skin and eyes, and can cause blistering on skin as well'],
# 'METHYLPARABEN':['Moderate','Effective at preventing microbial growth and germs such as bacteria and mold in skincare and cosmetic formulations','Itching, bumps and blisters, dry and scaly skin'],
# 'PROPYLPARABEN':['Safe','Used in cosmetics to prevent the growth of harmful bacteria and mold, in order to protect both the products and consumers',' can cause a variety of reactions to those with allergies. They are known to cause skin irritation'],
# 'POTASSIUM HYDROXIDE':['Toxic',' Used in small amounts in cosmetics to modulate the pH of a product','Contact with skin can cause irritation or severe burns and scarring with greater exposures.'],
# 'ALPHA-ISOMETHYL IONONE':['Safe','Is used in the formulation of aftershave lotions, bath products, bubble baths, hair care products, moisturizers, perfumes and colognes, shampoos and skin care products','has the potential to cause a skin reaction (such as red, bumpy, or itchy skin)'],
# 'BENZYL SALICYLATE':['Safe',' It is used as a solvent for crystalline synthetic musks and as a component and fixative in floral perfumes such as carnation','skin, eye, nose and throat irritants which can cause severe symptoms such as a burning sensation, nausea'],
# 'BUTYLPHENYL METHYLPROPIONAL':['Safe','Ssed in aftershave lotions, bath products, bubble baths, cleansing products, hair care products',' known dermal and respiratory irritant'],
# 'CITRONELLOL':['Safe','It has BB-cream like formula which offers instant tone perfection, elegant matte finish and efficient anti-UV B protection',' It might cause skin reactions or irritation in some people. When inhaled: Its LIKELY Unsafe to inhale citronella oil'],
# 'GERANIOL':['Safe','rt functions as a fragrance, masking (decreases or inhibits the basic odor in the product) and tonic (creates a feeling of well-being of the products on skin and hair) ingredient','A bit pour of itching'],
# 'HEXYL CINNAMAL':['Toxic','Used in perfumes and other beauty products as a fragrance additive.','The ingredient is known to cause contact allergy, which means that it can cause an allergic reaction to your skin'],
# 'COUMARIN':['Moderate','Used in the formulation of aftershave lotions, bath products, bubble baths, cleansing products, moisturizers','nausea, diarrhea or blurred vision may occur at first as your body adjusts to the medication']
# }